# Generated by Django 5.0.4 on 2024-04-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
